#!/bin/bash
#NOM    : Demo
#CLASSE : Process - LaboProcess 01-01
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo "Démonstration du programme Fork.c"
echo "----------------------------------"
echo
echo "Fork et variables locales"
echo -e "Exécution de ${E}./Fork${N} :"
./Fork
echo
echo -e "${C}             --> Enter pour continuer${N}"
read

