#NOM    : Makefile
#CLASSE : Process - LaboProcess 01-01
#OBJET  : demo du programme Fork.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Fork: Fork.c 
	#gcc Fork.c -o Fork
	gcc -std=c99 -Wall -pedantic-errors Fork.c -o Fork
	./Demo
clean:
	rm -f Fork fichier *~
