#NOM    : Makefile
#CLASSE : IPC - LaboIPC 02-02
#OBJET  : demo du programme AffContinu.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

AffContinu: AffContinu.c
	gcc -std=c99 -D _GNU_SOURCE -Wall --pedantic-errors AffContinu.c  -o AffContinu

clean:
	rm -f AffContinu semaphor.o *~

