#NOM    : Makefile
#CLASSE : ED - LaboED 02-02
#OBJET  : demo du programme FichierCreux.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


FichierCreux: FichierCreux.c
	gcc -std=c99 -Wall FichierCreux.c -o FichierCreux

clean:
	rm -f FichierCreux FichCreux.dat *~
