#NOM    : Makefile
#CLASSE : ED - LaboED 04-02
#OBJET  : demo du partitionnement d'un disque
#HOWTO	: make; make clean
#AUTEUR	: 


LectGPT : LectGPT.c
	@gcc -std=c99 -Wall LectGPT.c -o LectGPT -O0

clean:
	rm -f *~ LectGPT 
