#!/bin/bash
#NOM    : Demo
#CLASSE : FS - LaboProcess 02-02
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo "Démonstration du programme Zombie.c"
echo "-----------------------------------"
echo
echo "REMARQUE"
echo "--------"
echo
./Zombie
echo -e "${C}             --> Enter pour continuer${N}"
read
