#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 01-05
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
echo "Commande cat (avec argument) écrite en c : Mcat"
echo "-----------------------------------------------"
echo -e "Execution de ${E}./Mcat${N} : (Ctrl-D pour terminer !!!)"
./McatArgs
echo -e "${C}             --> Enter pour continuer${N}"
read
echo
echo ------------------------------
echo -e "Execution de ${E}./Mcat >file${N} : (Ctrl-D pour terminer !!!)"
./McatArgs >file
echo
echo ------------------------------
echo -e "Execution de ${E}Mcat file file${N} :"
./McatArgs file file
echo -e "${C}             --> Enter pour continuer${N}"
read
echo ------------------------------
echo -e "Execution de ${E}Mcat file | wc -l${N} :"
./McatArgs file | wc -l
echo -e "${C}             --> Enter pour continuer${N}"
read
echo ------------------------------
echo -e "Execution de ${E}Mcat Mcat.c | wc -l${N} :"
./McatArgs Mcat.c | wc -l
echo -e "${C}             --> Enter pour continuer${N}"
read
echo ------------------------------
echo -e "Execution de ${E}Mcat inexistant ddd${N} :"
./McatArgs inexistant ddd
echo -e "${C}             --> Enter pour continuer${N}"
read
echo ------------------------------
