#NOM    : Makefile
#CLASSE : ED - LaboED 01-05
#OBJET  : demo du programme Mcat.c, avec argument(s).
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


McatArgs: McatArgs.c 
	gcc -std=c99 -Wall McatArgs.c -o McatArgs

clean:
	rm -f McatArgs fichier *~
