#NOM    : Makefile
#CLASSE : ED - LaboED 01-03
#OBJET  : demo du programme Mcat.c, sans argument.
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


Mcat: Mcat.c 
	gcc -std=c99 -Wall Mcat.c -o Mcat

clean:
	rm -f Mcat fichier *~
