#NOM    : Makefile
#CLASSE : ED - LaboED 04-02
#OBJET  : lecture du partitionnement d'un disque
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


LectMBR : LectMBR.c
	@gcc -std=c99 -Wall LectMBR.c -o LectMBR -O0

clean:
	rm -f *~ LectMBR mbr
