#NOM    : Makefile
#CLASSE : IPC - LaboProcess 05-01
#OBJET  : demo du programme PipeShell.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

PipeShell: PipeShell.c 
	#gcc PipeShell.c -o PipeShell
	gcc -std=c99 -Wall -pedantic-errors PipeShell.c -o PipeShell

clean:
	rm -f PipeShell fichier *~
