#NOM    : Makefile
#CLASSE : ED - LaboED 03-02
#OBJET  : demo du programme Conf.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


Conf: Conf.c
	gcc -std=c99 -Wall Conf.c -o Conf

clean:
	@rm -f Conf Confidentiel *~
	@#chmod u-s Confidentiel
