#!/bin/bash
#NOM    : Demo
#CLASSE : FS - LaboFS 03-02
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011
C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
if [ $UID -eq 0 ]
then
	echo "quittez la session administrateur pour cette démonstrartion"
	exit 1
fi
echo "Démonstration de l'attaque via un programme SUID qui contient execlp"
echo "--------------------------------------------------------------------"
echo
echo '1) Création du fichier Confidentiel;'
echo -e "Exécution de ${E}echo CONFIDENTIEL > Confidentiel${N}"
echo CONFIDENTIEL > Confidentiel
echo '2) Modification des droits du fichier Confidentiel;'
echo -e "Exécution de ${E}chmod 600 Confidentiel${N}"
chmod 600 Confidentiel
echo '3) Modification des droits du programme Conf.'
echo -e "Exécution de ${E}chmod 4755 Conf${N}"
chmod 4755 Conf
echo '4) Vérification :'
echo -e "Exécution de ${E}pwd;ls -l Conf Confidentiel${N}"
pwd;ls -l Conf Confidentiel
echo
echo -e "${C}             --> Enter pour continuer${N}"
read
echo -n "Contenu du fichier Confidentiel : "; cat Confidentiel
echo -n "Exécution du programme Conf : "; ./Conf
echo "---------------------------------------------------------------------------------"
echo "Étant l'utilisateur propriétaire, CONFIDENTIEL s'affiche bien dans les deux cas"
echo "Il vous reste à vérifier, à partir d'un autre utilisateur"
echo -e "1) Que ${E}cat Confidentiel${N} n'affiche pas CONFIDENTIEL"
echo -e "2) Que ${E}./Conf${N} affiche CONFIDENTIEL"
echo "3) Que l'attaque SUID-execlp me permet d'exécuter n'importe quelle"
echo "   commande au nom du propriétaire du programme SUID qui contient execlp"
echo "----------------------------------------------------------------------------------"
echo -e "Pour ajouter un utilisateur ${E}user1${N} avec mot de passe ${E}user1${N}, dossier ${E}/home/user1${N}, groupe ${E}users${N} la commande administrateur :"
echo -e "${E}useradd -m -p user1 -d /home/user1 -g users user1${N}"
echo
echo -e "${C}             --> Enter pour continuer${N}"
echo
read
