#NOM    : Makefile
#CLASSE : FS - LaboProcess 03-02
#OBJET  : demo du programme Conf.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Conf: Conf.c
	#gcc Conf.c -o Conf
	gcc -std=c99 -Wall -pedantic-errors Conf.c -o Conf

clean:
	rm -f Conf Confidentiel *~

