#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 01-04
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
clear
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
clear
#Il faudra être root (0) pour exécuter ces commandes
if [ $UID -ne 0 ] ; then
	echo 
	echo "Pour ce script vous avez besoin des droits d'administration"
	echo "veuillez vous identifier en root et reessayer"
	echo 
	echo -e "${C}             --> Enter pour continuer${N}"
	read
	exit 1
fi
echo "Automatiser le partitionnement une opération dangereuse !!"
echo "----------------------------------------------------------"
echo
# partitions selon fdisk
fdisk -l
echo
echo "Si vous le souhaitez, insérez le device dont vous voulez afficher la table des partitions"
echo -e "${C}             --> Enter pour continuer${N}"
read
#les derniers avertissements du noyau
dmesg | tail
echo
#choix du device
while [ "$device" == "" ]
do
	echo -n "quel est le chemin correspondant au device (/dev/sdc, ...) ? "
	#lecture du clavier
	read device
done
echo
while [ "$rep" != "y" -a  "$rep" != "n" ]
do
	echo -n "Nous allons afficher les partitions de $device [y-n] ?"
	read rep
done

#fdisk et son stdin
if [ $rep == "y" ] ; then
	fdisk "$device" << CMD
p
q
CMD
	#fin de stdin
else
	echo vous avez abandonné ...
fi
echo
echo -e "${C}             --> Enter pour continuer${N}"
read
