#!/bin/bash
#NOM    : Demo
#CLASSE : Process - LaboProcess 04-03
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo -e "Démonstration du shell avec la commande ${E}ls -l > fichier${N}"
echo "----------------------------------------------------------"
echo
./ShellRedir <<EOF
ls -l > fichier 
exit
EOF
echo -e "${C}             --> Enter pour continuer${N}"; read
echo "Contenu du fichier 'fichier'"
echo "----------------------------"
echo -e "Exécution de la commande ${E}cat fichier${N}"
cat fichier
echo
echo -e "${C}             --> Enter pour continuer${N}"; read
#clear
echo -e "Démonstration libre du shell (${E}exit${N} pour terminer)"
echo "-------------------------------------------------"
echo
./ShellRedir
