#NOM    : Makefile
#CLASSE : Process - LaboProcess 04-03
#OBJET  : demo du programme ShellRedir.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

ShellRedir: ShellRedir.c
	#gcc ShellRedir.c -o ShellRedir
	gcc -std=c99 -Wall -pedantic-errors ShellRedir.c -o ShellRedir

clean:
	rm -f ShellRedir fichier *~

