#!/bin/bash
#NOM    : Demo
#CLASSE : IPC - LaboIPC 01-01
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
echo "Démonstration des programmes AlloueShm.c et FreeShm.c"
echo "-----------------------------------------------------"
echo -e "Exécution de ${E}./AlloueShm${N}"
./AlloueShm
echo -e "Exécution de ${E}./FreeShm${N}"
./FreeShm
echo -e "${C}             --> Enter pour continuer${N}"; read
