#!/bin/bash
#NOM    : Demo
#CLASSE : IPC - LaboIPC 02-04
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
echo "Démonstration du programme ProdCons.c"
echo "------------------------------------"
echo -e "Exécution de ${E}./cons&${N}"
./cons&
echo -e "\nExécution de ${E}ps | ./prod${N}"
ps | ./prod
echo -e "Tester via le clavier ${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}./cons&${N}"
./cons&
echo -e "\nExécution de ${E}./prod${N} - <Ctrl-D> pour l'arrêt"
./prod

