#!/bin/bash
#NOM    : Demo
#CLASSE : Process - LaboProcess 04-01
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo -e "Démonstration du shell avec la commande ${E}ls -ail${N}"
echo "-----------------------------------------------"
echo
./Shell <<EOF
ls -ail
exit
EOF
echo -e "${C}             --> Enter pour continuer${N}"; read
clear
echo -e "Démonstration du shell avec la commande ${E}head -4 Demo Makefile${N} suivie de ${E}lsblk${N}"
echo "--------------------------------------------------------------------------"
echo
./Shell <<EOF
head -4 Demo Makefile
lsblk 
exit
EOF
echo -e "${C}             --> Enter pour continuer${N}"; read
clear
echo -e "Démonstration du shell avec la commande ${E}ps ajfx${N}"
echo "--------------------------------------------------------------------------"
echo
./Shell <<EOF
ps ajfx
exit
EOF
echo -e "${C}             --> Enter pour continuer${N}"; read
clear
echo -e "Démonstration libre du shell (${E}exit${N} pour terminer)"
echo "-------------------------------------------------"
echo
./Shell

