#NOM    : Makefile
#CLASSE : Process - LaboProcess 04-01
#OBJET  : demo du programme Shell.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Shell: Shell.c
	#gcc Shell.c -o Shell
	gcc -std=c99 -Wall -pedantic-errors Shell.c -o Shell

clean:
	rm -f Shell *~

