#NOM    : Makefile
#CLASSE : ED - LaboED 03-01
#OBJET  : demo du programme ContenuRepertoire
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


ContenuRepertoire: ContenuRepertoire.c 
	gcc -std=c99 -Wall ContenuRepertoire.c -o ContenuRepertoire

clean:
	rm -f ContenuRepertoire *~
