#!/bin/bash
#NOM    : Demo
#CLASSE : Process - LaboProcess 06-02
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011
#	: M.Bastreghi, 03/2015

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo -e "Démonstration du shell avec les commandes ${E}ls -ail &${N} suivie ${E}ls -ail &${N}, de ${E}ls${N} et de ${E}ps${N}"
echo "------------------------------------------------------------------------"
echo
./ShellBackZ <<EOF
ls -ail &
echo coucou &
ps 
exit
EOF
echo -e "${C}             --> Enter pour continuer${N}"; read
echo
echo -e "Démonstration libre du shell avec traitement de & "
echo -e "faites précéder le caractère & par un espace : par exemple ${E}ls &${N}  (${E}exit${N} pour terminer)"
echo "-------------------------------------------------"
echo
./ShellBackZ
