#NOM    : Makefile
#CLASSE : Process - LaboProcess 06-02
#OBJET  : demo du programme ShellBackZ.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011
#	: M.Bastreghi, 03/2015

ShellBackZ: ShellBackZ.c
	#gcc ShellBackZ.c -o ShellBackZ
	gcc -std=c99 -Wall -pedantic-errors ShellBackZ.c -o ShellBackZ

clean:
	rm -f ShellBackZ *~

