#!/bin/bash
#NOM    : Demo
#CLASSE : IPC - LaboIPC 02-01
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
clear
echo "Démonstration du programme TrapCtrlc.c" 
echo "L'argument est le nombre de fois que l'on intercepte le Ctrl-c"
echo "--------------------------------------------------------------"
echo -e "Exécution de ${E}./TrapCtrlc 2${N} :"
./Sigaction 2
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}./TrapCtrlc${N} :"
./Sigaction
echo -e "${C}             --> Enter pour continuer${N}"; read
