#NOM    : Makefile
#CLASSE : IPC - LaboIPC 02-01
#OBJET  : demo du programme TrapCtrlc.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Sigaction: Sigaction.c 
	gcc -std=c99 -Wall -pedantic-errors Sigaction.c -o Sigaction

clean:
	rm -f Sigaction fichier *~
