#NOM    : Makefile
#CLASSE : Process - LaboProcess 04-02
#OBJET  : demo du programme ShellBack.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

ShellBack: ShellBack.c
	gcc -std=c99 -Wall -pedantic-errors ShellBack.c -o ShellBack

clean:
	rm -f ShellBack *~

