#!/bin/bash
#NOM    : Demo
#CLASSE : Process - LaboProcess 06-02
#OBJET  : réservé au Makefile
#AUTEUR	: J.C. Jaumain, 07/2011
#	: M.Bastreghi, 11/2017

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

clear
echo -e "Essayons de gérer tous les signaux"
echo -e "Testez : ${E}CTRL-C, kill -s${N} depuis une autre console"
echo -e "Exemple : kill pid, kill -10 pid, ..."
echo "------------------------------------------------------------------------"
echo
./Allsig
echo
echo -e "${C}             --> Enter pour continuer${N}"; read
