#NOM    : Makefile
#CLASSE : Process - LaboProcess 06-02
#OBJET  : demo du programme Allsig.c
#HOWTO	: make; make clean
#AUTEUR	: M.Bastreghi, 11/2017

Allsig: Allsig.c
	gcc -std=c99 -Wall -pedantic-errors Allsig.c -o Allsig

clean:
	rm -f Allsig *~

