#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 01-03
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
clear
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
echo "Démonstration du partitionnement du disk"
echo "----------------------------------------"
echo
echo "Il n'y a pas de démonstration automatisée"
echo "sur ce sujet"
echo
echo "Vous devez exécuter les commandes par vous-même"
echo
echo -e "${C}             --> Enter pour continuer${N}"
read

